version : "3.8"
services:

  client:
    build:
      context: ./app/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - TZ=America/Bogota #Puedes cambiar la zona horaria si es necesario
      - VITE_WS_URL=ws://backend:3000/ws/chat
      - VITE_API_URL=http://backend:3000/api/v1
    volumes:
      - ./app/client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Bogota
    volumes:
      - ./app/backend:/app
    depends_on:
      - ollama
  n8n:
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
    image:
      n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Bogota
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - ollama

  ollama:
    image:
      ollama/ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_LOAD_TIMEOUT=10m
      - OLLAMA_KEEP_ALIVE=30m
      - OLLAMA_NUM_PARALLEL=1
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:

