version : "3.8"
services:

  client:
    build:
      context: ./app/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - TZ=America/Bogota
    volumes:
      - ./app/client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TZ=America/Bogota
    volumes:
      - ./app/backend:/app
    depends_on:
      - ollama
  n8n:
    image:
      n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Bogota
    volumes:
      - ./n8n-data:/home/node/.n8n
    depends_on:
      - ollama

  ollama:
    image:
      ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:

